fimgs script will probe for unrar-free/rar/unrar-nonfree. fimgs man page updated.

diff --git a/src/fimgs b/src/fimgs
--- a/src/fimgs
+++ b/src/fimgs
@@ -1,21 +1,19 @@
 #!/bin/bash
 # $Id$
 
-# (c) 2007-2013 Michele Martone
+# (c) 2007-2017 Michele Martone
 
-# This is a modified version of the original fbgs script,by Gerd Knorr
-# and is capable of displaying pdf, eps, ps, and dvi files.
-# Now enhanced for viewing .cbr and .cbz files :)!
-#
-# Note : it won't probably work on bash, version < 3.0 because of regular expressions.
+# This is a modified version of the original fbgs script by Gerd Hoffman.
+# Note: it probably won't work on bash version < 3.0.
 
-# this script wants a temporary directory to stores rendered/wget'ed files
-# this directory is named after the process ID
+# This script uses a temporary directory to stores rendered/wget'ed files
+# This directory is named after the process ID
 
-# 20070925	regular expressions failed on some configurations, so were 'cut'.. :-(
-# 20090917	TODO: should work with no rar or no unzip
-# 20091214	TODO: and options to wget ?
-# 20090525	should use -o option to rename files to a known filename before loading them, in the temporary directory.
+# Possible improvements:
+# - regexp usage
+# - adapt to work withour rar or unzip
+# - give option to wget
+# - may add a "-o" option to specify $FIMTDPFX
 
 FIMSHMEM=/dev/shm
 FIMVARTD=/var/tmp
@@ -24,7 +22,8 @@ if test -d ${FIMSHMEM} -a -w ${FIMSHMEM} ; then
 else
 	FIMTMPDIR=$FIMVARTD
 fi
-DIR="${TMPDIR-$FIMTMPDIR}/fbps-$$"
+FIMTDPFX=fbps
+DIR="${TMPDIR-$FIMTMPDIR}/${FIMTDPFX}-$$"
 #GSRESOLUTION=""
 #GSRESOLUTION=${GSRESOLUTION:--r240x240}
 GSRESOLUTION=${GSRESOLUTION:-120x120}
@@ -44,26 +43,27 @@ trap "rm -rf $DIR" EXIT
 # export -f
 
 # as advised in man which, for mysterious reasons ( C compatible )
-which ()
-{
-	( alias; declare -f ; ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
-}
+# which ()
+# {
+# 	( alias; declare -f ; ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
+# }
 
 #export -f which
+FIMERRCV=255
 
 # checks if the first supplied argument is in the current $PATH
 function check_in_path()
 {
 	local cmd="$1";
 	[[ -z "$cmd" ]] && return 0
-	[[ -z $(which "$cmd" 2>/dev/null) ]] && return -1
+	[[ -z $(which "$cmd" 2>/dev/null) ]] && return ${FIMERRCV}
 	return 0
 }
 
 # output functions
 function info()  { echo '  [+]' "$@" 1>&2 ;  }
 function einfo() { echo '  [-]' "$@" 1>&2 ;  }
-function die() { einfo "ERROR : "$@ 1>&2 ; exit -1 ; }
+function die() { einfo "ERROR : "$@ 1>&2 ; exit ${FIMERRCV}; }
 
 # our favourite framebuffer viewing program :)
 FBI=fim
@@ -129,21 +129,28 @@ do
 			;;
 		-m)	shift
 cat << EOF
-.TH fimgs 1 "(c) 2007-2011 Michele Martone"
+.TH fimgs 1 "(c) 2007-2017 Michele Martone"
 .SH NAME
-fimgs - poor man's [http://]PostScript/pdf/dvi/cbr/rar/cbz/zip viewer for the linux
-framebuffer console
+fimgs - poor man's [http://]PostScript/pdf/dvi/cbr/rar/cbz/zip viewer based on fim
 .SH SYNOPSIS
 .B fimgs [ {fimgs-options} ] file [-- [{fim-options}]]
 .SH DESCRIPTION
 .B fimgs  
-is a simple wrapper script which takes a PostScript or pdf or .cbr or .rar or .cbz or .zip or .dvi or any of the above prefixed with http:// or https:// or ssh:// as input, renders the pages using ghostscript into a temporary directory and finally calls \fB $FBI\fP to display them.
+is a wrapper script which takes a PostScript or pdf or .cbr or .rar or .cbz or .zip or .dvi or any of the above prefixed with http:// or https:// or ssh:// as input, renders the pages using ghostscript into a temporary directory and finally calls \fB $FBI\fP to display them.
 
-In case of compressed archives (in zip or rar formats), the images are decompressed into a directory and displayed using \fB fim\fP.
-In this latter case, only images contained in the archive will be displayed (no nested archives or pdf's or ps's or dvi's).
+In case of compressed archives (in ZIP or RAR formats), the images are decompressed into a directory and displayed using \fB fim\fP.
+In this case, only images contained in the archive will be displayed (no nested archives or pdf's or ps's or dvi's).
 
-The temporary directory name is taken from the \$TMPDIR environment variable. 
-If unset, $FIMSHMEM and $FIMVARTD will be probed. 
+The temporary directory name will be of the form \$TMPDIR/$FIMTDPFX-\$\$.
+If the \$TMPDIR environment variable is unset, $FIMSHMEM and $FIMVARTD will be checked for existence and permissions. 
+The \$\$ above is the script process ID.
+The script shall delete the temporary directory when \fB fim\fP terminates.
+
+In order to uncompress RAR archives, fimgs will use 'unrar-free' or 'rar' or 'unrar-nonfree'.
+
+In order to uncompress ZIP archives, fimgs will use 'zip'.
+
+In order to fetch http:// or https:// prefixed URLS, 'wget' will be used.
 
 .SH OPTIONS
 To pass through options to \fB fim\fP, you may specify them after "--".
@@ -166,6 +173,7 @@ Will display a help message.
 .\" rendered with 100, 120 or 150 dpi (default is 75).
 .SH SEE ALSO
 fim(1), fimrc(1), gs(1), fbi(1), fbgs(1), bash(1)
+,zip(1), unrar-free(1), tar(1), gzip(1)
 .SH AUTHOR
 Michele Martone <dezperado _ GUESS _ autistici.org>. 
 EOF
@@ -202,7 +210,10 @@ done
 ##		HANDLING OF CBR AND CBZ ARCHIVES
 ###############################################################################
 UNCBZ="unzip" ; ZOPT="-x '*/*'" # suits for Info-ZIP implementation
-UNCBR="rar x"                   # suits for Alexander Roshal's RAR 3.51
+UNRAR="unrar-free"
+check_in_path $UNRAR || UNRAR="rar"
+check_in_path $UNRAR || UNRAR="unrar-nonfree"
+UNCBR="$UNRAR x"                   # suits for Alexander Roshal's RAR 3.51
 UNTAR="tar xf"
 UNTGZ="tar xzf"
 UNBZ="tar xjf"
